import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { mergeTypeDefs, mergeResolvers } from "@graphql-tools/merge";
import { loadFilesSync } from "@graphql-tools/load-files";
const __fileName = fileURLToPath(import.meta.url);
const __dirname = dirname(__fileName);
const allTypeDefs = loadFilesSync(join(__dirname, "./modules", "**", "schema.gql"), { extensions: ["gql"] });
const allResolvers = loadFilesSync(join(__dirname, "./modules", "**", "resolver.js"), { extensions: ["js"] });
const typeDefs = mergeTypeDefs(allTypeDefs);
const resolvers = mergeResolvers(allResolvers);
export { typeDefs, resolvers };
