query ListUser($id1: ID!, $id2: ID!) {
    firstUser: listUser(id: $id1) {
        ...fullUser
    },

    secondUser: listUser(id: $id2) {
        ...fullUser
    }
}

query ListUsers {
    listUsers {
        ...fullUser
    }
}

mutation CreateUser($userCreate: inputCreateUser!) {
    createUser(user: $userCreate) {
        ...fullUser
    }
}

mutation UpdateUser($userUpdate: inputUpdateUser!) {
    updateUser(user: $userUpdate) {
        ...fullUser
    }
}

mutation DeleteUser($id3: ID!) {
    deleteUser(id: $id3)
}

mutation DeleteUsers {
    deleteUsers
}

fragment fullUser on User {
    id
    cpf
    email
    name
    dateBirth
    password
    profile {
        id
        name
    }
}

# variables
# {
#   "id1": "1",
#   "id2": "2",
#   "id3": "1",

#   "userCreate": {
#     "cpf": "11111111111",
#     "email": "i@gmail.com",
#     "name": "Ian",
#     "dateBirth": "11/01/2021",
#     "password": "11223344",
#     "profile": "1",
#   },

#   "userUpdate": {
#     "id": "1",
#     "name": "Jose",
#     "dateBirth": "20/12/2000",
#     "password": "2222pP@a"
#   }
# }