version: '3'
services:
  api-graphql:
    image: gustavosilvasouza/user-management-system:v1
    container_name: user-management-system
    restart: always
    ports: 
      - 5000:3000
    networks:
      - api-graphql-network
networks:
  api-graphql-network:
    driver: bridge