type User {
    id: ID!,
    cpf: String!,
    email: String!,
    name: String!,
    dateBirth: String!,
    password: String!,
    profile: Profile!
},

input inputCreateUser {
    cpf: String!,
    email: String!,
    name: String!,
    dateBirth: String!,
    password: String!,
    profile: ID!
},

type Query {
    listUser(id: ID!): User,
    listUsers: [User]
},

type Mutation {
    createUser(user: inputCreateUser!): User,
    deleteUser(id: ID!): String!,
    deleteUsers: String!
}