type User {
    id: ID!,
    cpf: String!,
    email: String!,
    name: String!,
    dateBirth: String!,
    password: String!,
    profile: Profile!
},

type Query {
    listUser(id: ID!): User,
    listUsers: [User]
}