type User {
    id: ID!,
    cpf: String!,
    email: String!,
    name: String!,
    dateBirth: String!,
    password: String!,
    profile: Profile!
},

input inputCreateUser {
    cpf: String!,
    email: String!,
    name: String!,
    dateBirth: String!,
    password: String!,
    profile: ID!
},

input inputUpdateUser {
    id: ID!,
    name: String,
    dateBirth: String,
    password: String
},

type Query {
    listUser(id: ID!): User,
    listUsers: [User]
},

type Mutation {
    createUser(user: inputCreateUser!): User!,
    updateUser(user: inputUpdateUser!): User!,
    deleteUser(id: ID!): String!,
    deleteUsers: String!
}